# Generated by Django 4.0.5 on 2022-06-14 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='cost',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='journey',
            name='duration',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='journey',
            name='end',
            field=models.CharField(default=None, max_length=350),
        ),
        migrations.AddField(
            model_name='journey',
            name='legs',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='journey',
            name='modes',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='journey',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journey',
            name='start',
            field=models.CharField(default=None, max_length=350),
        ),
    ]
