# Generated by Django 4.0.5 on 2022-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0002_journey_cost_journey_duration_journey_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='times',
            field=models.JSONField(default=None),
        ),
    ]
