/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: bszlrd (https://sketchfab.com/bszlrd)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/sinonatrix-cockpit-3d8e9c08a07042c4964e9e826f407d92
title: Sinonatrix Cockpit
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/spaceship.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2.6, 0, 0]}>
        <group position={[-1.67, -4.34, -1.63]}>
          <mesh geometry={nodes['Sinonatrix_Cockpit-material'].geometry} material={materials['Sinonatrix.Cockpit']} />
        </group>
        <group position={[-1.67, -4.34, -1.63]}>
          <mesh geometry={nodes['Sinonatrix_Cockpit-material_1'].geometry} material={materials['Sinonatrix.Cockpit']} />
        </group>
        <group position={[0, -0.16, -0.71]}>
          <lineSegments geometry={nodes.Object_7.geometry} material={materials.material_0} />
          <mesh geometry={nodes['Sinonatrix_Cockpit-material_2'].geometry} material={materials['Sinonatrix.Cockpit']} />
        </group>
        <group position={[0.01, 0.24, -0.47]} rotation={[0.31, 0, 0]}>
          <mesh geometry={nodes['Sinonatrix_Cockpit-material_3'].geometry} material={materials['Sinonatrix.Cockpit']} />
        </group>
        <group position={[-1.67, -4.34, -1.63]}>
          <mesh geometry={nodes['Sinonatrix_Cockpit-material_4'].geometry} material={materials['Sinonatrix.Cockpit']} />
        </group>
        <group position={[0, 0.84, -0.13]}>
          <lineSegments geometry={nodes.Object_14.geometry} material={materials.material_0} />
          <mesh geometry={nodes['Sinonatrix_Cockpit-material_5'].geometry} material={materials['Sinonatrix.Cockpit']} />
        </group>
        <group position={[0.01, 0.24, -0.47]} rotation={[0.31, 0, 0]}>
          <mesh geometry={nodes['Sinonatrix_Screens-material'].geometry} material={materials['Sinonatrix.Screens']} />
        </group>
        <group position={[0, 0.84, -0.13]}>
          <mesh geometry={nodes['Sinonatrix_Screens-material_1'].geometry} material={materials['Sinonatrix.Screens']} />
        </group>
        <group position={[0, 0.84, -0.13]}>
          <mesh geometry={nodes['Sinonatrix_Transp-material'].geometry} material={materials['Sinonatrix.Transp']} />
        </group>
        <group position={[0.01, 0.24, -0.47]} rotation={[0.31, 0, 0]}>
          <mesh geometry={nodes['Screen_material_transparent-material'].geometry} material={materials.Screen_material_transparent} />
        </group>
        <group position={[-1.67, -4.32, -1.63]}>
          <mesh geometry={nodes['Hull-material'].geometry} material={materials.Hull} />
        </group>
        <group position={[0.33, 0.62, -0.42]} rotation={[0.84, 0, 0]}>
          <mesh geometry={nodes['Sinonatrix_Cockpit-material_6'].geometry} material={materials['Sinonatrix.Cockpit']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spaceship.gltf')
